{
 "title": "Spring Boot Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(process_uptime_seconds, instance)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(process_uptime_seconds{instance=~\"$instance\"}, application)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=~\"$instance\", application=~\"$application\"}"
    }
   ]
  },
  {
   "title": "Heap Used %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\",instance=~\"$instance\",application=~\"$application\"})*100/sum(jvm_memory_max_bytes{area=\"heap\",instance=~\"$instance\",application=~\"$application\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\",instance=~\"$instance\",application=~\"$application\"})*100/sum(jvm_memory_max_bytes{area=\"nonheap\",instance=~\"$instance\",application=~\"$application\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=~\"$instance\",application=~\"$application\"}",
     "legendFormat": "System"
    },
    {
     "expr": "process_cpu_usage{instance=~\"$instance\",application=~\"$application\"}",
     "legendFormat": "Process"
    }
   ]
  },
  {
   "title": "Threads (Live/Daemon)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{instance=~\"$instance\",application=~\"$application\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_daemon_threads{instance=~\"$instance\",application=~\"$application\"}",
     "legendFormat": "Daemon"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "HTTP Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{instance=~\"$instance\",application=~\"$application\",uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Response Time (s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{instance=~\"$instance\",application=~\"$application\",exception=\"None\",uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{instance=~\"$instance\",application=~\"$application\",exception=\"None\",uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  }
 ]
}