apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: ecommerce
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
    - name: kafka-legacy
      port: 9092
      targetPort: 29092
      protocol: TCP
  selector:
    app: kafka