# Deployment Kafka
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: ecommerce
  labels:
    app: kafka
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      enableServiceLinks: false
      initContainers:
      - name: init-permissions
        image: busybox:1.36
        command: ["sh", "-c", "mkdir -p /var/lib/kafka/data && chown -R 1000:1000 /var/lib/kafka/data || true"]
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
      containers:
      - name: kafka
        image: "confluentinc/cp-kafka:7.6.1"
        command: ["/bin/bash", "-lc", "set -x; unset PORT port; exec /etc/confluent/docker/run"]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-service.ecommerce.svc.cluster.local:29092"
        ports:
        - containerPort: 9092
          name: kafka-external
        - containerPort: 29092
          name: kafka-internal
        - containerPort: 29093
          name: controller
        - containerPort: 9101
          name: jmx
        envFrom:
        - configMapRef:
            name: kafka-config
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "kafka-broker-api-versions --bootstrap-server localhost:29092"
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "kafka-broker-api-versions --bootstrap-server localhost:29092"
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
      volumes:
      - name: kafka-data
        persistentVolumeClaim:
          claimName: kafka-data-pvc
      restartPolicy: Always