apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: discovery-server-ingress
  namespace: ecommerce
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: discovery.192.168.2.232.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: discovery-server
            port:
              number: 8761
