# Jenkins CD Pipeline - Staging Configuration

# This file contains staging-specific overrides for the CD pipeline
# Apply these configurations to deploy services to staging environment

apiVersion: v1
kind: ConfigMap
metadata:
  name: staging-config
  namespace: ecommerce-staging
data:
  # Environment-specific configuration
  SPRING_PROFILES_ACTIVE: "staging"
  LOG_LEVEL: "DEBUG"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server.ecommerce-staging.svc.cluster.local:8761/eureka"
  
  # Staging-specific database connections
  MYSQL_HOST: "mysql-service.ecommerce-staging.svc.cluster.local"
  MONGO_HOST: "mongo-service.ecommerce-staging.svc.cluster.local"
  
  # Kafka configuration for staging
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service.ecommerce-staging.svc.cluster.local:29092"
  
  # Reduced resource settings for staging
  JAVA_OPTS: "-Xmx256m -Xms128m"

---
# Staging resource quotas to prevent resource exhaustion
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: ecommerce-staging
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "20"
    services: "10"

---
# Network policy for staging environment
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: staging-network-policy
  namespace: ecommerce-staging
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ecommerce-staging
    - namespaceSelector:
        matchLabels:
          name: monitoring
  egress:
  - to: []